name: testing_in_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5

  #A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  flutter_screenutil: ^5.9.3



  flutter_bloc: ^9.1.1
  
  cached_network_image: ^3.4.1
  #networking package, supports Interceptors, Aborting and canceling a request,
  dio: ^5.9.0
  #retrofit.dart is an dio client generator using source_gen and inspired by Chopper and Retrofit.
  retrofit: ^4.7.3

  retrofit_generator: any

  #network calls in a pretty, easy to read format.
  pretty_dio_logger: ^1.4.0

  #Annotations for the freezed code-generator. This package does nothing without freezed too.
  freezed_annotation: ^3.1.0

  #allows to decouple the interface from a concrete implementation and to access the concrete implementation from everywhere in your App"
  get_it: ^8.2.0

  shared_preferences: ^2.5.3
  
  #A package that automatically generate a loading widget from your own widget.
  redacted: ^1.0.13
  
  # hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  infinite_scroll_pagination: ^5.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
     
  #A build system for Dart code generation and modular compilation.c
  build_runner: any
 
  #Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: any
  
  hive_generator: any

 
flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-ExtraBold.ttf
          weight: 800      
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/manrope/Manrope-ExtraLight.ttf
          weight: 200
        

